### ISSUE TITLE
Cannot find module tslib after upgrading to 6.1.5

### ISSUE THREAD

**Issue by chandrasekhar1996** [downshift-js/downshift#1309]
- `downshift` version: 6.1.5
- `node` version: 12.22.4
- `npm` (or `yarn`) version: 6.14.4

**Relevant code or config**

```javascript
```

**What you did**:
Updated the downshift version from 6.1.2 to 6.1.5
**What happened**:
When I updated the package, I got the error : 
Cannot find module tslib in downshift.cjs.js. 
Is this something that should be added as a dependency in the package.json of downshift? 

**Reproduction repository**:

**Problem description**:

**Suggested solution**:

**Comment by jooj123** [comment]
I am also getting this: 

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'tslib' in '/var/www/node_modules/downshift/dist'
```

**Comment by silviuaavram** [comment]
Is this happening in 6.1.6?

**Comment by AfrazHussain** [comment]
Yes, happens in 6.1.6 as well. I've downgraded back to 6.1.3 and it works fine.

**Comment by silviuaavram** [comment]
Any idea how we could fix this?

**Comment by chandrasekhar1996** [comment]
I noticed that this package uses 
@rollup/plugin-typescript
The [Readme](https://github.com/rollup/plugins/tree/master/packages/typescript#install) for this package mentions that both typescript and tslib is a peer dependency and needs to be installed separately. Since downshift doesn't install tslib separately, I am assuming that is what is causing the issue

I am currently logging off now but will create a PR tomorrow morning with the new dependency

**Comment by silviuaavram** [comment]
Great, thanks for looking into it @chandrasekhar1996 ! Looking forward to the PR!
